### ISSUE TITLE
KeyError: u'Non-existent config key: BODY_UV_RCNN Error

### ISSUE THREAD

**Issue by tiandiao123** [ronghanghu/seg_every_thing#7]
Hi guys:
   I have some trouble debugging the following error. I tried some ways to fix it such as checking detectron PATHONPATH, but still doesn't doesn't work me. Can someone help me find out what is the problem here?

```
(caffe2_env) (/data1/wdyli/miniconda3) [wdyli@TENCENT64 ~/densepose]$ python tools/infer_simple.py     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml     --output-dir /data1/wdyli/densepose/DensePoseData/sample_output/     --image-ext jpg     --wts https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl     /data1/wdyli/densepose/DensePoseData/demo_data/demo_im.jpg
Found Detectron ops lib: /data1/wdyli/miniconda2/lib/python2.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 87, in main
    merge_cfg_from_file(args.cfg)
  File "/data1/wdyli/densepose/detectron/detectron/core/config.py", line 1135, in merge_cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/data1/wdyli/densepose/detectron/detectron/core/config.py", line 1185, in _merge_a_into_b
    raise KeyError('Non-existent config key: {}'.format(full_key))
KeyError: u'Non-existent config key: BODY_UV_RCNN'

```

**Comment by ronghanghu** [comment]
Are you using this repository or the [DensePose repository](https://github.com/facebookresearch/DensePose)? If you are using DensePose, you should post issues in that repo.
